import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { FileCheck2, GraduationCap, Utensils } from "lucide-react"

const documents = ["Certificado de Habilitações Literárias", "Fotocópia da Cédula/Bilhete de Identidade", "Cartão de Vacina Actualizado", "Atestado Médico", "4 fotografias tipo passe", "Cópia do B.I. do Encarregado de Educação"]
const fees = [["Matrícula para Iniciação", "Grátis"], ["Matrícula / Confirmação da 1.ª à 6.ª classe", "15.000 Kz"], ["Estudo Orientado do Primário à 8.ª Classe", "8.300 Kz"], ["Confirmação / Matrícula da 7.ª à 9.ª classe", "20.000 Kz"], ["Orientação Vocacional I (9.ª Classe)", "11.000 Kz"], ["Cartão de Estudante", "3.500 Kz"]]

export function Enrollment() {
  return <section id="matriculas" className="bg-card py-20"><div className="container mx-auto px-4"><div className="mx-auto mb-12 max-w-3xl text-center"><p className="mb-3 font-mono text-sm font-semibold uppercase tracking-widest text-secondary">Ano lectivo 2026/2027</p><h2 className="mb-4 text-3xl font-bold text-primary md:text-4xl">Matrículas e reconfirmações</h2><p className="text-muted-foreground">Ensino Geral, com toda a documentação e os valores oficiais.</p></div><div className="grid gap-8 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-3 text-primary"><FileCheck2 />Documentos necessários</CardTitle><CardDescription>Prepare os seguintes documentos.</CardDescription></CardHeader><CardContent><ul className="grid gap-4 sm:grid-cols-2">{documents.map((item) => <li key={item} className="flex gap-3 text-sm"><span className="mt-2 size-2 shrink-0 rounded-full bg-secondary" />{item}</li>)}</ul></CardContent></Card><Card><CardHeader><CardTitle className="flex items-center gap-3 text-primary"><GraduationCap />Valores de matrícula</CardTitle><CardDescription>Taxas oficiais de 2026/2027.</CardDescription></CardHeader><CardContent className="p-0"><div className="divide-y divide-border">{fees.map(([label, value]) => <div key={label} className="flex justify-between gap-4 px-6 py-3 text-sm"><span>{label}</span><strong className="shrink-0 text-secondary">{value}</strong></div>)}</div></CardContent></Card></div><div className="mx-auto mt-8 grid max-w-5xl gap-4 md:grid-cols-2"><Card className="border-secondary/30 bg-secondary/10"><CardContent className="flex gap-3 p-5 text-sm"><Utensils className="shrink-0 text-secondary" /><p><strong>Material de Iniciação e 1.ª Classe:</strong> 8.000 Kz/trimestre (24.000 Kz/ano). Inclui Inglês e Umbundo. Merenda da Iniciação à 2.ª Classe: <strong>grátis</strong>.</p></CardContent></Card><Card className="border-primary/20 bg-primary/5"><CardContent className="p-5 text-sm"><strong>Fora do prazo:</strong> matrícula/confirmação fora de Julho e Agosto acresce 10.000 Kz.</CardContent></Card></div></div></section>
}
