export type ActivitySection = "defesas" | "eventos" | "festivais" | "visitas" | "formaturas"
export type MediaType = "image" | "video"

export interface ActivityMedia {
  id: string
  type: MediaType
  url: string
  thumbnail?: string
  title: string
  description?: string
  date: string
  category: ActivitySection
  altText: string
}

export const activitiesData: ActivityMedia[] = [
  // Defesas de Cursos
  {
    id: "defesa-1",
    type: "image",
    url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop",
    title: "Defesa TCC - Informática 2024",
    description: "Alunos apresentando seus trabalhos de conclusão de curso.",
    date: "15/06/2024",
    category: "defesas",
    altText: "Alunos apresentando defesa de TCC",
  },
  {
    id: "defesa-2",
    type: "image",
    url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop",
    title: "Defesa - Enfermagem",
    description: "Avaliação de projetos de enfermagem.",
    date: "10/06/2024",
    category: "defesas",
    altText: "Defesa de projeto de enfermagem",
  },
  {
    id: "defesa-3",
    type: "image",
    url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop",
    title: "Defesa - Análises Clínicas",
    description: "Apresentação de pesquisas em análises clínicas.",
    date: "08/06/2024",
    category: "defesas",
    altText: "Defesa de projeto de análises clínicas",
  },
  {
    id: "defesa-4",
    type: "image",
    url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop",
    title: "Defesa Técnico de Electrónica",
    description: "Projetos finais de técnica em electrónica.",
    date: "05/06/2024",
    category: "defesas",
    altText: "Defesa de projeto de electrónica",
  },
  {
    id: "defesa-5",
    type: "image",
    url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop",
    title: "Defesa - Fisioterapia",
    description: "Apresentação de casos clínicos em fisioterapia.",
    date: "02/06/2024",
    category: "defesas",
    altText: "Defesa de projeto de fisioterapia",
  },
  {
    id: "defesa-6",
    type: "image",
    url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop",
    title: "Defesa - Radiologia",
    description: "Projetos de técnica radiológica e imagiologia.",
    date: "30/05/2024",
    category: "defesas",
    altText: "Defesa de projeto de radiologia",
  },

  // Eventos Escolares
  {
    id: "evento-1",
    type: "image",
    url: "https://images.unsplash.com/photo-1540575467063-178f50002cbc?w=800&h=600&fit=crop",
    title: "Dia do Aluno",
    description: "Celebração anual do dia do aluno com atividades especiais.",
    date: "12/05/2024",
    category: "eventos",
    altText: "Dia do aluno - celebração escolar",
  },
  {
    id: "evento-2",
    type: "image",
    url: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop",
    title: "Semana da Saúde",
    description: "Semana dedicada a temas de saúde e bem-estar.",
    date: "10/05/2024",
    category: "eventos",
    altText: "Semana da saúde escolar",
  },
  {
    id: "evento-3",
    type: "image",
    url: "https://images.unsplash.com/photo-1540575467063-178f50002cbc?w=800&h=600&fit=crop",
    title: "Conferência de Tecnologia",
    description: "Palestra sobre inovações tecnológicas.",
    date: "08/05/2024",
    category: "eventos",
    altText: "Conferência de tecnologia",
  },
  {
    id: "evento-4",
    type: "image",
    url: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop",
    title: "Workshop de Criatividade",
    description: "Encontro de criatividade e inovação.",
    date: "05/05/2024",
    category: "eventos",
    altText: "Workshop de criatividade",
  },
  {
    id: "evento-5",
    type: "image",
    url: "https://images.unsplash.com/photo-1540575467063-178f50002cbc?w=800&h=600&fit=crop",
    title: "Jornada de Orientação",
    description: "Aconselhamento para alunos sobre carreiras.",
    date: "02/05/2024",
    category: "eventos",
    altText: "Jornada de orientação profissional",
  },
  {
    id: "evento-6",
    type: "image",
    url: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=600&fit=crop",
    title: "Dia da Responsabilidade Social",
    description: "Atividades de responsabilidade social e comunitária.",
    date: "29/04/2024",
    category: "eventos",
    altText: "Dia da responsabilidade social",
  },

  // Festivais
  {
    id: "festival-1",
    type: "image",
    url: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=600&fit=crop",
    title: "Festival da Cultura Africana",
    description: "Grande celebração das tradições culturais africanas.",
    date: "21/04/2024",
    category: "festivais",
    altText: "Festival de cultura africana",
  },
  {
    id: "festival-2",
    type: "image",
    url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&h=600&fit=crop",
    title: "Festival de Música",
    description: "Apresentações musicais de alunos e convidados.",
    date: "18/04/2024",
    category: "festivais",
    altText: "Festival de música escolar",
  },
  {
    id: "festival-3",
    type: "image",
    url: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=600&fit=crop",
    title: "Festa de Artes",
    description: "Exposição e apresentações de artes plásticas e performativas.",
    date: "15/04/2024",
    category: "festivais",
    altText: "Festa de artes escolar",
  },
  {
    id: "festival-4",
    type: "image",
    url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&h=600&fit=crop",
    title: "Festival de Cinema",
    description: "Exibição de filmes produzidos por alunos.",
    date: "12/04/2024",
    category: "festivais",
    altText: "Festival de cinema escolar",
  },
  {
    id: "festival-5",
    type: "image",
    url: "https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=800&h=600&fit=crop",
    title: "Festival de Gastronomia",
    description: "Mostra de culinária africana e internacional.",
    date: "10/04/2024",
    category: "festivais",
    altText: "Festival de gastronomia",
  },
  {
    id: "festival-6",
    type: "image",
    url: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&h=600&fit=crop",
    title: "Festival Científico",
    description: "Exposição de projetos e experimentos científicos.",
    date: "08/04/2024",
    category: "festivais",
    altText: "Festival científico",
  },

  // Visitas de Estudo
  {
    id: "visita-1",
    type: "image",
    url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop",
    title: "Visita ao Hospital Central",
    description: "Alunos de saúde visitam o Hospital Central.",
    date: "25/03/2024",
    category: "visitas",
    altText: "Visita ao hospital",
  },
  {
    id: "visita-2",
    type: "image",
    url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop",
    title: "Visita ao Museu Nacional",
    description: "Exploração cultural no museu nacional.",
    date: "22/03/2024",
    category: "visitas",
    altText: "Visita ao museu",
  },
  {
    id: "visita-3",
    type: "image",
    url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop",
    title: "Visita Empresa de Tecnologia",
    description: "Alunos de informática visitam empresa de tecnologia.",
    date: "20/03/2024",
    category: "visitas",
    altText: "Visita à empresa de tecnologia",
  },
  {
    id: "visita-4",
    type: "image",
    url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop",
    title: "Visita Centro de Pesquisa",
    description: "Conhecer instalações de pesquisa científica.",
    date: "18/03/2024",
    category: "visitas",
    altText: "Visita ao centro de pesquisa",
  },
  {
    id: "visita-5",
    type: "image",
    url: "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=600&fit=crop",
    title: "Visita Laboratório Clínico",
    description: "Alunos de análises clínicas visitam laboratório.",
    date: "15/03/2024",
    category: "visitas",
    altText: "Visita ao laboratório clínico",
  },
  {
    id: "visita-6",
    type: "image",
    url: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop",
    title: "Visita Parque Tecnológico",
    description: "Tour no parque tecnológico da cidade.",
    date: "13/03/2024",
    category: "visitas",
    altText: "Visita ao parque tecnológico",
  },

  // Formaturas
  {
    id: "formatura-1",
    type: "image",
    url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop",
    title: "Formatura 2024 - Enfermagem",
    description: "Solenidade de formatura dos alunos de Enfermagem.",
    date: "05/03/2024",
    category: "formaturas",
    altText: "Formatura de enfermagem",
  },
  {
    id: "formatura-2",
    type: "image",
    url: "https://images.unsplash.com/photo-1540575467063-178f50002cbc?w=800&h=600&fit=crop",
    title: "Formatura 2024 - Informática",
    description: "Cerimônia de formatura dos técnicos em informática.",
    date: "03/03/2024",
    category: "formaturas",
    altText: "Formatura de informática",
  },
  {
    id: "formatura-3",
    type: "image",
    url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop",
    title: "Formatura 2024 - Análises Clínicas",
    description: "Solenidade de formatura dos alunos de análises clínicas.",
    date: "01/03/2024",
    category: "formaturas",
    altText: "Formatura de análises clínicas",
  },
  {
    id: "formatura-4",
    type: "image",
    url: "https://images.unsplash.com/photo-1540575467063-178f50002cbc?w=800&h=600&fit=crop",
    title: "Formatura 2024 - Electrónica",
    description: "Cerimônia de conclusão dos técnicos em electrónica.",
    date: "28/02/2024",
    category: "formaturas",
    altText: "Formatura de electrónica",
  },
  {
    id: "formatura-5",
    type: "image",
    url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop",
    title: "Formatura 2024 - Fisioterapia",
    description: "Solenidade de formatura em Fisioterapia.",
    date: "26/02/2024",
    category: "formaturas",
    altText: "Formatura de fisioterapia",
  },
  {
    id: "formatura-6",
    type: "image",
    url: "https://images.unsplash.com/photo-1540575467063-178f50002cbc?w=800&h=600&fit=crop",
    title: "Formatura 2024 - Recursos Humanos",
    description: "Cerimônia de formatura de Gestão de Recursos Humanos.",
    date: "24/02/2024",
    category: "formaturas",
    altText: "Formatura de recursos humanos",
  },
]

export const sectionLabels: Record<ActivitySection, string> = {
  defesas: "Defesas de Cursos",
  eventos: "Eventos Escolares",
  festivais: "Festivais",
  visitas: "Visitas de Estudo",
  formaturas: "Formaturas",
}

export const sectionColors: Record<ActivitySection, { bg: string; text: string }> = {
  defesas: { bg: "bg-blue-100", text: "text-blue-700" },
  eventos: { bg: "bg-purple-100", text: "text-purple-700" },
  festivais: { bg: "bg-pink-100", text: "text-pink-700" },
  visitas: { bg: "bg-green-100", text: "text-green-700" },
  formaturas: { bg: "bg-amber-100", text: "text-amber-700" },
}
